name: CI Flow

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI flow

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Publish to Codecov
        uses: codecov/codecov-action@v4
        with:
          # Codecov backend may be unstable
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}